### ISSUE TITLE
能否提供一个nodejs的webhook示例？

### ISSUE THREAD

**Issue by longxianlin** [beecloud/beecloud-webhook#12]
谢谢了。
我使用leancloud的nodejs云引擎

**Comment by quietbamboo** [comment]
这个应该是比较标准的操作，就是使用你的nodejs框架来接收一个HTTP的POST请求。leancloud有接收POST请求的demo吗？

**Comment by quietbamboo** [comment]
有问题请与我们联系   https://beecloud.cn/about/contact.php
