### ISSUE TITLE
用的python的demo处理webhook，返回了succes还是会继续回调

### ISSUE THREAD

**Issue by wangask0040** [beecloud/beecloud-webhook#13]

**Comment by quietbamboo** [comment]
你返回的是“succes” 还是 “success”，必须严格返回“success”才行，返回的时候字符串长度是7，前后的双引号也不能加

**Comment by quietbamboo** [comment]
另外，出现同一个订单重复的webhook是可能的，这个可能渠道那边发给我们就是重复的，在webhook文档里说了，需要商户自己做webhook的判重的处理。
