### ISSUE TITLE
请问如何告知BeeCloud调用success或fail

### ISSUE THREAD

**Issue by hustKiwi** [beecloud/beecloud-webhook#2]
我仔细看了文档，并没有对webhook需要返回值的说明。但是当success或因 `sign ` 验证错误fail时，我应该如何通知BeeCloud？

类似，`Ping++` 在webhook文档中就做了详细说明，通过200或500的状态码表征成功或失败：https://pingxx.com/guidance/webhooks#receive-event

**Comment by hustKiwi** [comment]
@quietbamboo @Danzeer

**Comment by hustKiwi** [comment]
sorry，我找到了。真是不明显...
> 返回"success"字符串代表正确接收并确认了结果，其他所有返回都代表需要继续重传。

**Comment by quietbamboo** [comment]
我们会对文档重新布局一下，你反应的问题也反映出我们文档的一些不足，感谢
